### ISSUE TITLE
Invalid argument for foreach(): _easy_breadcrumb_check_excluded_path()

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/easy_breadcrumb#8] opened 2020-12-08 07:56 UTC
Got this error message every time I see a node:

```
Warning: Invalid argument supplied for foreach() a _easy_breadcrumb_check_excluded_path() (línia 444 de /.../modules/easy_breadcrumb/easy_breadcrumb.module).
```

**Comment by laryn** [comment] 2020-12-18 20:23
Closing as duplicate of https://github.com/backdrop-contrib/easy_breadcrumb/issues/3

**Closed as completed by laryn** 2020-12-18 20:23 UTC
